### ISSUE TITLE
Custom port number

### ISSUE THREAD

**Issue by cooljimy84** [btotharye/mycroft-homeassistant#12]
So I've got Mycroft skill installed. However in the logs it says its connecting to myserver.domain.co.UK:8123:443
I have SSL set to true, as I'm using let's encrypt, but on port 8123.
Is it possible to do ?

**Comment by btotharye** [comment]
Sorry I should make that part more clear you don't need to specify the port I already take care of that in the code so you only need the below, if you don't have SSL setup use false, if you do have SSL setup it still should use 443 I would think, unless you are using a bit of a different setup.

```
"HomeAssistantSkill": {
    "host": "hass.mydomain.com",
    "password": "mysupersecrethasspass",
    "ssl": true
  }
```
Let me know if that makes sense or if I misunderstood the question/issue.

**Comment by cooljimy84** [comment]
OK, so use SSL true assumes port 443 HTTPS,
And false uses the default 8123 HTTP.

I'm using SSL on port 8123, just to make it complex !

**Comment by btotharye** [comment]
yea try that and let me know if it doesn't work, I think the way I have it coded it should still work without needing to actually put your port in since that doesn't change.

**Comment by cooljimy84** [comment]
So with just the server address and ssl set to false i get
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))

with the server address with :8123 at the end and ssl set to false i get
InvalidURL: Failed to parse: mqtt.cooljimy84.co.uk:8123:8123

So i'm gonna edit __init__.py and change the ssl port from 443 to 8123 as that will work. As it's ssl on port 8123.

**Comment by cooljimy84** [comment]
that worked, for me.
If i get time tomorrow i'll see if i can to a pull request ( is that right ? or should i fork ? ) and see if i can make a config item to set

**Comment by btotharye** [comment]
Sure yea you can fork the code then modify it in your own version and test it then push up a PR.  I honestly hadn't done this yet because it hadn't come up.  I just use SSL on mine which uses 443 by default so it doesn't route to a 8123.

Thanks

**Comment by cooljimy84** [comment]
I think i've done it right (the fork, edit and merge)
