### ISSUE TITLE
Failure to setup using latest core 18.2.2 enclosure 1.3.0 (new SD image)

### ISSUE THREAD

**Issue by cooljimy84** [btotharye/mycroft-homeassistant#28]
So i've installed the skill and added the details to my details to the skill in the mycroft portal.
Host adress (spelling mistake there)
mqtt.MYDNSNAME.co.uk

Password
12345

Port Number
8123

Use SSL
ticked

Verify SSL certificate
ticked

But i'm getting this from the mycroft-skills.log

```
09:20:54.505 - mycroft.skills.core:load_skill:143 - ERROR - Failed to load skill: mycroft-homeassistant
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/mycroft_core-18.2.2-py2.7.egg/mycroft/skills/core.py", line 115, in load_skill
    skill = skill_module.create_skill()
  File "/opt/mycroft/skills/mycroft-homeassistant/__init__.py", line 506, in create_skill
    return HomeAssistantSkill()
  File "/opt/mycroft/skills/mycroft-homeassistant/__init__.py", line 117, in __init__
    self._setup()
  File "/opt/mycroft/skills/mycroft-homeassistant/__init__.py", line 130, in _setup
    int(self.settings.get('portnum')),
ValueError: invalid literal for int() with base 10: ''
```

**Comment by cooljimy84** [comment]
Also seems to wipe the config from the skills settings in the mycroft skills page, unless that is expected due to errors ?

**Comment by lowEagle** [comment]
Besides the configuration in your mycroft.conf, also set them directly within the skills directory (probably /opt/mycroft/skills/mycroft-homeassistant). 
There is a file called settings.json with some presets for the connection. However, the port is an empty string, therefore the ValueError occurs. By adding your settings to this file the plugin will work.

**Comment by cooljimy84** [comment]
So it's uploading my local version to the mycloud settings cloud... hence not working and blanking it out ?

Testing now

**Comment by lowEagle** [comment]
I'm not sure how exactly the settings are synced. A few days ago I tried setting it up and started by applying the settings in the home.mycroft.ai interace. However this exact error occured and setting my values within the named file was the solution.
I have not tested weather the values need to be correct or if the eventually will be overwritten by the one set in the cloud.

Good luck setting it up. Mycroft + Home-Assistant is an awesome combination :)

**Comment by cooljimy84** [comment]
I had it running before the major release, then my SD card died (been running since kickstarter sent them out) so just resetting everything up.

**Comment by btotharye** [comment]
Hey guys I just recently set back up my mycroft instance and I used the home.mycroft.ai settings and I find if I restart the services or at least the skill services after applying it it typically shows up after that.

**Comment by btotharye** [comment]
There was also the issue yesterday where all the devices unpaired so I'm not sure if that is related, have you repaired your device from the last outage @cooljimy84

**Comment by cooljimy84** [comment]
I did find i had to repair it after an hour, i'm also getting a boot loop at the mo (which doesn't help when the unit just reboots when your try to do things !)
Just switching to unstable now see if that helps with my reboot issue ( i get an error about Duplicate mycroft-skills found
Hack reboot...)

**Comment by cooljimy84** [comment]
nope unstable branch still boot loops me....

I'l leave this here and update once i fix my other issues.
