### ISSUE TITLE
Issue loading skill on picroft

### ISSUE THREAD

**Issue by dcmtmc** [btotharye/mycroft-homeassistant#34]
error in __init__.py missing import  from ha_client import HomeAssistantClient
So I change it to
from .ha_client import HomeAssistantClient

That seemed to have fixed my issue.

**Comment by btotharye** [comment]
Thanks I fixed this, was a typo from all the refactoring I did to the code yesterday.  Try it and verify for me.

**Comment by nielstron** [comment]
Somehow my IDE works with `ha_client` and doesn't with `.ha_client`. Using python 3.6, which are your versions?

**Comment by btotharye** [comment]
I use python 3.6
