### ISSUE TITLE
Lights Based on Room Location

### ISSUE THREAD

**Issue by btotharye** [btotharye/mycroft-homeassistant#4]
Setup location based lights varying on where in the house the person is.  So turn on lights, and if you are in office they come on in the office.

**Comment by BongoEADGC6** [comment]
I was actually going to start working this project again. Glad someone picked it up as well.

**Comment by btotharye** [comment]
Yep we haves a lot working and more coming and I built a home assistant component for mycroft too.   We had someone do German translation too

**Comment by BongoEADGC6** [comment]
Awesome. I'm going to take a look at the changes and continue implementing. I see you started the sensors already. 

What's interesting is the HomeAssistant just created a new module for Mycroft. I wonder if there's some good collaboration that can be done with their team.

**Comment by btotharye** [comment]
I know I made that module for home assistant :)

**Comment by BongoEADGC6** [comment]
I was thinking about this and maybe it can related to groups, but with HAss, there's no differentiation of groups from what I can tell. A group is a group, not like a 'light' group or a 'switch' group. 
So I wonder how to call the api in a way that says 'all the lights in this group' besides just looping through the devices in a group and hope for the best.
