### ISSUE TITLE
Cannot connect to HA server

### ISSUE THREAD

**Issue by GregPK** [btotharye/mycroft-homeassistant#53]
Hey there. Love the concept.

I'm trying to connect to my local network. Mycroft is running on my desktop and the HA is running on a RPi under the desk. 

What I did:
- I've setup a password for the API in HA configuration (tested it with `wget`) and
- set the options for `mycroft-homeassistant` to the local HA address with the proper port
- disabled SSL options

Problem:
- Getting "Error occured when trying to connect to local homeassistant server" and then "The home assistant server is offline" from Mycroft.

Questions:
- is this local setup even possible?
- where can I find a logfile to debug the connections?

**Comment by nielstron** [comment]
> is this local setup even possible?

I don't see why your setup shouldn't work

If you disabled SSL, make sure that SSL is also not at all enabled at the HA Server (HA refuses non SSL connections if turned on)

**Comment by GregPK** [comment]
SSL is disabled on the HA server.

Configured via websettings.

**Comment by nielstron** [comment]
It may be that this is due to #54. Did you change the websettings more than once?

**Comment by nielstron** [comment]
Did you try the newest version of `mycroft-homeassistant`? It will provide you with more detailed error messages

**Comment by btotharye** [comment]
this should be resolved on the master branch, thanks
