### ISSUE TITLE
Support URL as an alternative to host/port

### ISSUE THREAD

**Issue by ndarilek** [btotharye/mycroft-homeassistant#58]
Hi. I just created a Mycroft addon for [Hass.io](https://www.home-assistant.io/hassio/). Hassio addons use a permission system for granting access to permissions and services. From the [addon configuration docs](https://developers.home-assistant.io/docs/en/hassio_addon_config.html):

    homeassistant_api | bool | no | This add-on can access to Hass.io Home-Assistant REST API proxy. Use http://hassio/homeassistant/api.

IOW, if in my addon configuration I specify `"homeassistant_api": true`, which I do, then HA is available at http://hassio/homeassistant/api. This isn't compatible with specifying a host and/or port.

It'd be nice if I could directly specify a full URL in the configuration. I understand you'd need to keep the current host/port configuration for compatibility, but as things stand it doesn't look like I can get this skill running in the context of Hassio.

Thanks!

**Comment by btotharye** [comment]
I'll look into this but I run hass.io with no issues on this skill the way it is designed.

**Comment by RudolfRendier** [comment]
@ndarilek Can your hass.io addon be found online? I would like to run mycroft as addon in hass.io too.

**Comment by btotharye** [comment]
Just so you are aware there is already a mycroft component in home assistant I already wrote...

**Comment by ndarilek** [comment]
I think there's a bit of confusion and ambiguation here. I don't want to 
hijack the issue, but I do want to answer the question asked of me:


[Hass.io](https://www.home-assistant.io/hassio/) != Home Assistant, and 
a Mycroft Hass.io addon != a Home Assistant component. Sorry, not trying 
to patronize, this genuinely confused me for a long time. They could do 
a better job of naming things IMO. :)


As for my addon, find it 
[here](https://gitlab.com/ndarilek/hassio-mycroft). Unfortunately 
doesn't work without the accompanying PulseAudio addon installed, so if 
your Hass.io instance does anything else with audio, that's something to 
be aware of. I should probably announce it publicly since I've used it 
reliably for months now.


Anyhow, let's continue the discussion elsewhere so we're not clogging 
this issue tracker. :) Thanks for your interest.

**Comment by btotharye** [comment]
Closing as I’m not really sure the ask here since you built a separate add on for hass that is really different from what this is used for.

Thanks
