### ISSUE TITLE
Is this a broken repo now. 

### ISSUE THREAD

**Issue by montanaman2017** [btotharye/mycroft-homeassistant#64]
It seems you had some great intentions for having mycroft in Home Assistant, but both have changed a lot and as such I don't see any new updates on your github.   Do you have any updated notes for using mycroft with Hass.io (Home Assistant...the so called easy version)...or OpenHab or..? 

thanks!
P.S.  I have a Mycroft Mark 1

**Comment by btotharye** [comment]
Right now I have stopped working in this due to other paid projects sucking up a lot of my time

**Comment by andlo** [comment]
> Do you have any updated notes for using mycroft with Hass.io

This super skill IS working and also working on mycroft 18.08

**Comment by btotharye** [comment]
I'm continuing to work on it now that things have slowed down a little for me.

Thanks

**Comment by montanaman2017** [comment]
@btotharye   you said, 

> 

> I'm continuing to work on it now that things have slowed down a little for me.
> 
> Thanks

If I only I could express how exciting this is especially if you can document it a bit more.  I really want to get this up and running.
