### ISSUE TITLE
Login attempt error

### ISSUE THREAD

**Issue by NathanLKing** [btotharye/mycroft-homeassistant#65]
Howdy. 

I'm trying set up and use your cool Skill.

I've set up HASS, all works great. I've installed your skill, no errors indicated. 
When I go to use it in Mycroft it shows this error in the HASS gui:
Login attempt or request with invalid authentication from (ip address)

And Mycroft states "Sorry, entity "tv" wasn't found." or something similar.

Any suggestions?

Thanks.

Nathan

**Comment by lowEagle** [comment]
Heyho,

Maybe I am able to help:
A few days ago I ran into similar problems after updating my local home-assistant to 0.77.3. As far as I can see home-assistant moved from a simple password to a user+password based authentication, that breaks some external program's access.

Do you have set an API-password in the home-assistant config (configuration.yaml ... http: api_password)? I had not but after setting it and adding the same password to the skill-settings everything worked again.

Maybe this will work for you too ;)

**Comment by NathanLKing** [comment]
howdy @lowEagle 
Thanks for responding.

I'd like to follow your instructions, but I'm having difficulty. 

What exactly do I add in to configuration.yaml?
http: is commented out at the moment, I assume I should remove the # and add in some code, but I need to know specifically what that is. Additionally, I assume you mean adding the same password to the skills setting - the fields in https://home.mycroft.ai/  ?

**Comment by lowEagle** [comment]
Near the top of configuration.yaml there should be the following entries:
[...]
# Enables configuration UI
config:
http:
 api_password: SET-YOUR-PASSWORD-HERE
 [...]

The same password should be added to the fields in the mycroft configuration. Of course the the IP of the machine running home-assistant needs to be added as well as the port (the standard-port is 8123).

**Comment by cooljimy84** [comment]
I would test, but the sdcard on my pi died, 2nd one in a year.
Got an SSD usb adapter so should be running and test by the end of the week.

**Comment by btotharye** [comment]
this has been resolved now with #77 so you can now use the tokens option.
