### ISSUE TITLE
Mycroft comfinrms command, Hass.io doesn't reflect it actually happening

### ISSUE THREAD

**Issue by pat1121** [btotharye/mycroft-homeassistant#69]
Just installed this and giving it a test. I get a confirmation from Mycroft, IE:

Me: Hey Microft, turn on the garage light.
Mycroft: Turned on garage light

I then check Hass.io, and my garage light is still in the off position, with no indication it was turned on.

This is literally my first attempt at anything inside Hass.io or Mycroft, so it very well could be me...I'm also a complete novice to all of this, so that should help tons with finding a solution :)

Thx in advance for any help.

**Comment by andlo** [comment]
I do not see this behavior - in my installation it works just fine.
Does the garage light actual turn on? 
Can you turn light on on hass.io ?

**Comment by pat1121** [comment]
Thanks for the quick reply. The lights do actually turn on, and stayed on, however it had nothing to do with this mycroft skill. I had an error in my configuration.yaml file in hass.io with the states of my switch not sending back properly, making hass.io think the switch was off when it was in fact on. I corrected the yaml file and all is well now!

**Comment by andlo** [comment]
That sounds good :) please remember to close this issue :)
