### ISSUE TITLE
Skill not compliant with latest HA login

### ISSUE THREAD

**Issue by dvpfig** [btotharye/mycroft-homeassistant#70]
Hi, 

Excellent work on this home assistant skill. 

I have the latest version of HA and HASSIO and the login procedure has changed considerably, now needing both username and passw (instead of only passw) to login to home assistant. 

The mycroft skill is not configured to edit the username, hence the Home Assistant rejects the login with error "the home assistant server did not accept the configured password". 

/Daniel

**Comment by andlo** [comment]
You should still be able to use legacy api password. 

https://www.home-assistant.io/docs/authentication/providers/#legacy-api-password

But I agree that skill has to be changed to use new uhentifiction before the legacy api password is deprecated.

**Comment by btotharye** [comment]
Anyone is more than welcome to submit a PR right now I have other paid projects taking up my time

**Comment by andlo** [comment]
I would if i could :) 

I am trying to find information on what to do - but I am not a programmer...There is still some time until the legacy api password is removed from HA.

**Comment by dvpfig** [comment]
The legacy option lets me to at least try out the skill, thanks. 
If I can make it to learn enough to propose a change, will do since it is a very useful skill. However at the moment, I'm still just at the very surface of knowing what it is possible to do.

**Comment by btotharye** [comment]
Can anyone confirm if this issue still exists or if this issue needs to remain opened?

**Comment by andlo** [comment]
Ill say it dosnt exist, and issue could be closed.
