### ISSUE TITLE
Skill settings not being saved on home.mycroft.ai

### ISSUE THREAD

**Issue by asrrin29** [btotharye/mycroft-homeassistant#72]
in the "Skills" section of home.mycroft.ai where the settings are kept for hostname, password, etc. the settings do not save.  I'm running the new picroft stretch release.

**Comment by andlo** [comment]
I have seen this to. Did think it were problems on home.mycroft.ai. But I see it still, but cant figure out why.

**Comment by andlo** [comment]
I did remove the skill from all my devises. Removed the settings on home.mycroft.ai (by pressing the round arrows in upper right coner by the skill settings. 
Then I did a install of the skill on one of the devises - and checked it worked, and then the rest of the devises. And now - as far as I can se the settings remain on home.mycroft.ai.

One thereory could be that there yesterday were some backend issues, and that interfeered when you and I dis install the skill, and the skill settings were setup on home.mycroft.ai. I actualy dont know. 

Can you confirm that you can get it to save the settings now or after a reinstall of the skill ?

**Comment by asrrin29** [comment]
Thanks for the response.  I've tried to uninstall and reinstall, and the behavior persists.  also of note, and what probably should be a new issue, is that the Utterance to install no longer appears to work, and I must use "msm install" + the github repo to install.  Sounds like this skill needs to be updated to 18.08 in order to work...

**Comment by andlo** [comment]
yah - the Utterance wil nt work until the skill is aproved into 18.08 repo.

There has been lots of talk about this strange behavior whith settings not remembered at the mattermost channels.

**Comment by asrrin29** [comment]
I was able to do a workaround by renamming the settingsmeta.json file in the skills folder and manually entering my settings int he settings.json file.  I now have a working skill, I'll just have to uninstall and reinstall when the skills gets updated.

**Comment by cooljimy84** [comment]
Think I'm gonna have to do the same, it just wipes it in skills section on the website every so often.

**Comment by btotharye** [comment]
this should be resolved now

**Comment by tekmad** [comment]
I have this problem with a new install picroft (18.8.4), seems to loose the settings after a fews hours.
