### ISSUE TITLE
Settings are not persistent

### ISSUE THREAD

**Issue by g3rb3n** [btotharye/mycroft-homeassistant#80]
After saving my settings in home.mycroft.ai the home assistant skill works for ten to fifteen minutes after which the settings are reverted to the defaults. I am not sure if this is an mycroft-homeassistant issue or an issue on the mycroft server, it just seems to only happen with this skill and not with other skills.

**Comment by tekmad** [comment]
Me too, seems the same as issue #72 https://github.com/btotharye/mycroft-homeassistant/issues/72 the workaround there helped me for now.

**Comment by g3rb3n** [comment]
Thank you for the reference. I have modified the code so that the local settings do not get overwritten when the home.mycroft.ai settings have an empty host address. Now my home assistant skill stays connected and strangely my home.mycroft.ai settings also stay set.

It seems as if settings are kept in sync in two directions from home.mycroft to devices and also reverse from devices to home.mycroft.

The modified version can be found here: https://github.com/g3rb3n/mycroft-homeassistant
