### ISSUE TITLE
Brand new out the box mycroft, trying to install but i get the following error.

### ISSUE THREAD

**Issue by cooljimy84** [btotharye/mycroft-homeassistant#9]
sudo pip install -r requirements.txt
Requirement already satisfied: fuzzywuzzy==0.14.0 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 1))
Collecting python-Levenshtein==0.12.0 (from -r requirements.txt (line 2))
  Using cached python-Levenshtein-0.12.0.tar.gz
Requirement already satisfied: setuptools in /usr/local/lib/python2.7/site-packages (from python-Levenshtein==0.12.0->-r requirements.txt (line 2))
Building wheels for collected packages: python-Levenshtein
  Running setup.py bdist_wheel for python-Levenshtein ... error
  Complete output from command /usr/local/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ZrkX2R/python-Levenshtein/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpOKGdUjpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-armv7l-2.7
  creating build/lib.linux-armv7l-2.7/Levenshtein
  copying Levenshtein/StringMatcher.py -> build/lib.linux-armv7l-2.7/Levenshtein
  copying Levenshtein/__init__.py -> build/lib.linux-armv7l-2.7/Levenshtein
  running egg_info
  writing requirements to python_Levenshtein.egg-info/requires.txt
  writing python_Levenshtein.egg-info/PKG-INFO
  writing namespace_packages to python_Levenshtein.egg-info/namespace_packages.txt
  writing top-level names to python_Levenshtein.egg-info/top_level.txt
  writing dependency_links to python_Levenshtein.egg-info/dependency_links.txt
  writing entry points to python_Levenshtein.egg-info/entry_points.txt
  reading manifest file 'python_Levenshtein.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files matching '*pyc' found anywhere in distribution
  warning: no previously-included files matching '*so' found anywhere in distribution
  warning: no previously-included files matching '.project' found anywhere in distribution
  warning: no previously-included files matching '.pydevproject' found anywhere in distribution
  writing manifest file 'python_Levenshtein.egg-info/SOURCES.txt'
  copying Levenshtein/_levenshtein.c -> build/lib.linux-armv7l-2.7/Levenshtein
  copying Levenshtein/_levenshtein.h -> build/lib.linux-armv7l-2.7/Levenshtein
  running build_ext
  building 'Levenshtein._levenshtein' extension
  creating build/temp.linux-armv7l-2.7
  creating build/temp.linux-armv7l-2.7/Levenshtein
  arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c Levenshtein/_levenshtein.c -o build/temp.linux-armv7l-2.7/Levenshtein/_levenshtein.o
  Levenshtein/_levenshtein.c:99:20: fatal error: Python.h: No such file or directory
   #include <Python.h>
                      ^
  compilation terminated.
  error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for python-Levenshtein
  Running setup.py clean for python-Levenshtein
Failed to build python-Levenshtein
Installing collected packages: python-Levenshtein
  Running setup.py install for python-Levenshtein ... error
    Complete output from command /usr/local/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ZrkX2R/python-Levenshtein/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-3YYJXE-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/site/python2.7/python-Levenshtein:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-armv7l-2.7
    creating build/lib.linux-armv7l-2.7/Levenshtein
    copying Levenshtein/StringMatcher.py -> build/lib.linux-armv7l-2.7/Levenshtein
    copying Levenshtein/__init__.py -> build/lib.linux-armv7l-2.7/Levenshtein
    running egg_info
    writing requirements to python_Levenshtein.egg-info/requires.txt
    writing python_Levenshtein.egg-info/PKG-INFO
    writing namespace_packages to python_Levenshtein.egg-info/namespace_packages.txt
    writing top-level names to python_Levenshtein.egg-info/top_level.txt
    writing dependency_links to python_Levenshtein.egg-info/dependency_links.txt
    writing entry points to python_Levenshtein.egg-info/entry_points.txt
    reading manifest file 'python_Levenshtein.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*pyc' found anywhere in distribution
    warning: no previously-included files matching '*so' found anywhere in distribution
    warning: no previously-included files matching '.project' found anywhere in distribution
    warning: no previously-included files matching '.pydevproject' found anywhere in distribution
    writing manifest file 'python_Levenshtein.egg-info/SOURCES.txt'
    copying Levenshtein/_levenshtein.c -> build/lib.linux-armv7l-2.7/Levenshtein
    copying Levenshtein/_levenshtein.h -> build/lib.linux-armv7l-2.7/Levenshtein
    running build_ext
    building 'Levenshtein._levenshtein' extension
    creating build/temp.linux-armv7l-2.7
    creating build/temp.linux-armv7l-2.7/Levenshtein
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c Levenshtein/_levenshtein.c -o build/temp.linux-armv7l-2.7/Levenshtein/_levenshtein.o
    Levenshtein/_levenshtein.c:99:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/local/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ZrkX2R/python-Levenshtein/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-3YYJXE-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/site/python2.7/python-Levenshtein" failed with error code 1 in /tmp/pip-build-ZrkX2R/python-Levenshtein/

**Comment by btotharye** [comment]
Did you perform the apt-get install python-dev mentioned in the readme before this?  That should have taken care of this error.  Let me know if so and I'll see what is going on.

**Comment by btotharye** [comment]
Also if this is a mark 1 I think there is a known issue with msm not installing the requirements right so you may want to run pip install -r requirements.txt on the /opt/mycroft/skills/mycroft-homeassistant folder

**Comment by cooljimy84** [comment]
yep, it was the python-dev

Sorry

**Comment by btotharye** [comment]
Not a problem glad to hear that is all it was.
